name: EnchantLimit
main: Genboy\EnchantLimit\EnchantLimit
version: 0.0.1
api: 3.11.6
load: POSTWORLD
author: Genboy
description: Limit Enchantments plugin
website: https://github.com/genboy
commands:
 enchantlimit:
  description: "Limit Enchantments plugin"
  usage: "Set the enchantment limit for each item: /enchantlimit set <number>, info: /enchantlimit info"
  permission: enchantlimit.command
 el:
  description: "Limit Enchantments plugin (short cmd)"
  usage: "Set the enchantment limit for each item: /enchantlimit set <number>, info: /enchantlimit info"
  permission: el.command
permissions:
 enchantlimit:
  default: true
  description: "Example root enchantlimit permission node"
  children:
   enchantlimit.command:
    default: true
    description: "Allows the use of /enchantlimit"
 el:
  default: true
  description: "Example root el permission node"
  children:
   el.command:
    default: true
    description: "Allows the use of /el"
